name: Python CI

on:
  push:
    branches:
      - feature_fix_salesmen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Merge with another branch
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout other-branch
        git merge --no-commit develop

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run pytest
      run: pytest --only-changed
