name: Merge and Test

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout developer branch
      uses: actions/checkout@v2
      with:
        ref: developer

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: 
        python -m pip install --upgrade pip
        pip install pytest

    - name: Merge feature branch
      run: 
        git merge --no-commit feature_fix_salesmen

    - name: Run tests
      run: 
        pytest --changed-only
